### ISSUE TITLE
Visually highlight graphs

### ISSUE THREAD

**Issue by vhf** [zazuko/SPEX#1]
This tool is saving me a lot of time, it's awesome!

Not sure it can be done but something that would be useful would be showing the graphs. Here's an example where `Tak Job Run` are in one graph, `Log LogEvent` in another one:

![Screenshot 2020-05-19 at 15 00 20](https://user-images.githubusercontent.com/2022803/82329772-19a31c00-99e2-11ea-8aaf-33416efbb741.png)

**Comment by BenjaminHofstetter** [comment]
the assumption that a shape is only in a named graph is wrong. e.g. Fedlex they have a named graph per subject.
