### ISSUE TITLE
Define proper discovery mechanism for predefined SHACL shapes and viewport definition

### ISSUE THREAD

**Issue by ktk** [zazuko/SPEX#25]
IANA [defines](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) `.well-known/void`. That should be the entry point and in there we should follow the basic [VoID](https://www.w3.org/TR/void/) and/or schema.org [Dataset](https://schema.org/Dataset) syntax to point to data.

* In there we somehow point to SHACL shapes.
* Another place defines where Viewports should be

**Comment by l00mi** [comment]
Also compare https://github.com/zazuko/SPEX/discussions/32#discussioncomment-334764

**Comment by martinmaillard** [comment]
Some things that are not clear to me:
- What should `.well-known/void` point to? Does it point to one `Dataset`, that is then split into multiple datasets using `void:subset` if the endpoint/graph contains multiple distinct datasets?
- I didn't find anything related to describing the structure of the data with `void` as we want to do it with shapes. It defines some [structural metadata](https://www.w3.org/TR/void/#structural), but it's quite different.
- They already use `void:classPartition` and `void:propertyPartition` (subproperties of `void:subset`) to describe "all triples that describe entities that have this class" (https://www.w3.org/TR/void/#class-property-partitions). It looks somewhat similar to what we want to do with *Viewpoints*/*Viewports*... but not really

**Comment by l00mi** [comment]
The `classPartition` and `propertyPartition` look quite promising? @bergos what do you think?

**Comment by martinmaillard** [comment]
The issue with them is that they only allow creating a `subset` that contains *one* class or property. Not really what we want.

**Comment by l00mi** [comment]
I read it as you can add multiple "partitions" to a dataset which allows you define one "view".

**Comment by bergos** [comment]
I guess we have to use http://rdfs.org/ns/void#DatasetDescription or/and http://schema.org/DataCatalog as an entry point. There can be multiple `Dataset`s, but there should be only one `DatasetDescription`. But how to attach it? I also don't see any property in `void` that looks suitable. We may also need some properties and classes for the viewports. I would propose to define a new namespace.

`void:*Partition` could be an alternative to my schema.org based set proposal. But if we use it, we will have additional `Dataset`s for include/exclude sets. Is that ok? People/machines could get lost what is an actual dataset and what is just a set for a spex viewport.

**Comment by l00mi** [comment]
I rather would add mulitple `Datasets` and then use a new namespace and class to addinally make it clear that its used as a viewport. E.g. `spex:ViewPort`?

**Comment by l00mi** [comment]
@martinmaillard 
1. Can you please try to define the structure (with an example), without any namespaces for the ViewPort use case. Then we will give input on the final solution.

2. @bergos will make a proposition how the SHACL shapes are attached to the `.well-known/void`

**Comment by bergos** [comment]
Maybe it's easier to make the entry point not based on a class instead we just define that it must be attached to `/.well-know/void`.

The property used to point to the shapes would be defined in the `spex:` namespace. `spex:shape` should match with the shacl shape use case, but would also work for any other data that describes the shape of the data (not planned, just in case).

That property could be used to point to the shape for each class. But it would be also possible to use one shape as a collection for all class-related shapes. With an additional type, this collection shape could be flagged as the default shape. That would allow having alternative shapes for any future use cases, like actual data vs. model.

```turtle
</.well-know/void>
  spex:shape [ a sh:NodeShape, spex:DefaultShapes;
    sh:node [ a sh:NodeShape;
      sh:targetClass <https://permits.ld.admin.ch/schema/Profession>;
      sh:property [ a sh:PropertyShape;
      ], [ a sh:PropertyShape;
      ]
    ], [ a sh:NodeShape;
      sh:targetClass <https://permits.ld.admin.ch/schema/...>;
      sh:property [ a sh:PropertyShape;
      ], [ a sh:PropertyShape;
      ]
    ]
  ].
```

**Comment by martinmaillard** [comment]
I'll use the `spex` namespace for the prototype, but I was wondering: doesn't that introduce a really bad pattern where every tool requires specific metadata to describe a dataset?

Other thing: I'm a bit surprised that you used a surrounding `sh:NodeShape` and that classes are linked with `sh:node`. Can you explain the reasoning behind this?

Now to extend your example with viewpoints, I would see something like:

```turtle
</.well-know/void>
  spex:shape [ 
    a sh:NodeShape, spex:DefaultShapes;
    sh:node [ a sh:NodeShape;
      sh:targetClass <https://permits.ld.admin.ch/schema/Profession>;
      sh:property [ a sh:PropertyShape;
      ], [ a sh:PropertyShape;
      ]
    ], [ a sh:NodeShape;
      sh:targetClass <https://permits.ld.admin.ch/schema/...>;
      sh:property [ a sh:PropertyShape;
      ], [ a sh:PropertyShape;
      ]
    ] ;
  ] ;
  spex:viewpoint [
    a spex:ViewPoint ;
    schema:name "Only the Profession class" ;
    spex:includes <https://permits.ld.admin.ch/schema/Profession> ;
  ] ;
  spex:viewpoint [
    a spex:ViewPoint ;
    schema:name "Everything but the Profession class" ;
    spex:excludes <https://permits.ld.admin.ch/schema/Profession> ;
  ] ;
.
```
@bergos in the [discussion](https://github.com/zazuko/SPEX/discussions/32#discussioncomment-496154), you mention using one more level and `hasPart` for the items in the `include` and `exclude` sets. I'm not sure I understand the advantage.

**Comment by l00mi** [comment]
@martinmaillard did you implement something in this regard now? If yes can you point os to it that we can potentially officiate it.

**Comment by martinmaillard** [comment]
Nothing done yet

**Comment by l00mi** [comment]
So do you need anything more from here to advance on SPEX?

**Comment by martinmaillard** [comment]
Time 😄 

And if you have some inputs about the RDF structure I shared above, that's welcome too.

**Comment by martinmaillard** [comment]
Let's say we keep the additional nesting level for the shapes. As @bergos mentioned, it could make it easier to allow multiple versions of the schema later (or something like that).

I don't really like the use of `sh:NodeShape` for the top-most level and `sh:node` to point to shapes. I feel like it's trying really hard to use SHACL, but the result doesn't mean anything. If I try to interpret it, I think it would mean "to satisfy this shape, the target must conform to all these sub-shapes".

Here's what I propose:

```diff
</.well-know/void> spex:shape [ 
-    a sh:NodeShape, spex:DefaultShapes;
+   a spex:DefaultShapes ;
-    sh:node [ 
+   schema:hasPart [
      a sh:NodeShape;
      sh:name "Profession" ;
      sh:targetClass <https://permits.ld.admin.ch/schema/Profession>;
    ], [ 
      a sh:NodeShape;
      sh:name "Something" ;
      sh:targetClass <https://permits.ld.admin.ch/schema/Something>;
    ] ;
  ] ;
```

**Comment by martinmaillard** [comment]
One more question: which URI should I use for the `spex` prefix?

**Comment by l00mi** [comment]
I would go for `https://described.at/spex/` @sandhose @ludovicm67 where is the repo for described.at ? then we can add some triples there also.

**Comment by ludovicm67** [comment]
The repo for described.at is here: https://gitlab.zazuko.com/docker/described.at
