### ISSUE TITLE
Not showing data when running against Fuseki on localhost

### ISSUE THREAD

**Issue by RobertHenschel** [zazuko/SPEX#27]
When I use SPEX to explore a local endpoint, I can see the schema just fine, but cannot see any data. The endpoint is running Fuseki Version 3.16.0. on HTTP. I have tried inserting two different sets of triples but in either case can only see the schema but not the data.
Fuseki logs the query that SPEX is sending to list the triples, and when I run that query in the fuseki query interface it correctly lists the triples.

**Comment by martinmaillard** [comment]
I did some testing and it seems to be related to the `GRAPH` behavior. Fixing it right away.
