### ISSUE TITLE
Cannot load endpoint on small screens 

### ISSUE THREAD

**Issue by magdasalatka** [zazuko/SPEX#29]
The scrollbar is missing under "Options" tab. 
This disables user to load load graph when screen is smallere than the content

![image](https://user-images.githubusercontent.com/48995317/96276178-ef767a00-0fd2-11eb-99b4-8c6316cfe9ad.png)

**Comment by martinmaillard** [comment]
Fixed in https://github.com/zazuko/SPEX/commit/22e893fdad1a51fe667d91e1dd9faf1edab304e3
