### ISSUE TITLE
Autocomplete in Options/Graph does not list all graphs

### ISSUE THREAD

**Issue by magdasalatka** [zazuko/SPEX#35]
Example:
* endpoint: https://ld.stadt-zuerich.ch/query
* graph not listed: https://lindas.admin.ch/stadtzuerich/stat/views

**Comment by martinmaillard** [comment]
The autocomplete is supposed to load more graphs when you scroll to the end of the list. Is that not working?
It's not ideal but some endpoint have thousands of graphs so we can't really load all of them upfront.

**Comment by magdasalatka** [comment]
No, that does not load than 10 graphs. Here we are at 23 graphs, ans you can only see first 10.

**Comment by martinmaillard** [comment]
Which browser are you using?

**Comment by magdasalatka** [comment]
Chrome: Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by martinmaillard** [comment]
Weird, I tried with Chrome and it also works for me 🤔

**Comment by martinmaillard** [comment]
Changed the graph selector, this issue should not be relevant anymore
