### ISSUE TITLE
Missing scrollbar

### ISSUE THREAD

**Issue by magdasalatka** [zazuko/SPEX#36]
For longer graphs, there is no scrollbar available.
This leads to unexpected behaviour, where mouse scroll means "zoom in/out". Keyboard arrows also do not allow for moving up/down the page.

Example:
https://zazuko.github.io/SPEX/#/?url=https%3A%2F%2Fld.stadt-zuerich.ch%2Fquery&graph=https%3A%2F%2Flindas.admin.ch%2Fstadtzuerich%2Fstat%2Fviews&prefixes=wdt%3Ahttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F&forceIntrospection=false

**Comment by martinmaillard** [comment]
The controls are similar to a geographical map component. You can move around by clicking and dragging.

But adding support for arrow keys is not a bad idea.

**Comment by martinmaillard** [comment]
Arrow keys are now supported ;)

**Comment by l00mi** [comment]
Closing in favor of the now supported other interaction methods, I considered shortly to add a graphical element to hint this, but it seems intuitive enough that there is no need.
