### ISSUE TITLE
Prefixes and Base are not used

### ISSUE THREAD

**Issue by VladimirAlexiev** [zazuko/SPEX#37]
https://gist.github.com/VladimirAlexiev/94eb90d237a8bd772ba692737c2f108d#file-model-ttl defines base and prefixes:
```
@base        <https://transparency.ontotext.com/resource/>.
@prefix tr:  <https://transparency.ontotext.com/resource/tr/>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

##### powerUnit

<eic/32W001100100217D>
  tr:dateImplemented  "2014-11-12"^^xsd:date;
  tr:notationAlt  "NPP_KOZLODUY";
  tr:biddingZone  <eic/10YCA-BULGARIA-R>;
```
But neither of them are used, resulting in very wide nodes: https://gist.github.com/VladimirAlexiev/94eb90d237a8bd772ba692737c2f108d#gistcomment-3798169

**Comment by ktk** [comment]
This is an issue in https://github.com/zazuko/rdfjs-elements/issues/55.

Base is not supported in the RDF/JS parsers/serializers so unless someone fixes it there, this won't be supported.
