### ISSUE TITLE
better layout

### ISSUE THREAD

**Issue by VladimirAlexiev** [zazuko/SPEX#40]
SPEX layout is quite primitive, and there's no control
- https://gist.github.com/VladimirAlexiev/94eb90d237a8bd772ba692737c2f108d#gistcomment-3798165
- https://gist.github.com/VladimirAlexiev/94eb90d237a8bd772ba692737c2f108d#gistcomment-3798169

@ktk "auto-layouting is super hard, any feature requests need to be financed or contributed :)"

Graph layout is hard if you do it yourself, but can be easy if you use GraphViz or PlantUML.
See what they can do at https://www.graphviz.org/gallery/ and https://real-world-plantuml.com/.
My `rdfpuml` uses `plantuml` object (or is it class) diagrams to render RDF.

PlantUML by default uses GraphViz (which is a set of C executables) for layout, but includes other options:
- java: https://plantuml.com/smetana02
- js: http://plantuml.com/vizjs

Most people use Graphviz `dot`, but it has other parts as well, see https://www.graphviz.org/documentation/.
`Dotty` is an interactive editor, but I don't know how old technologies it uses.

https://www.google.com/search?q=site%3Agraphviz.org+javascript returns interesting graphviz+javascript tools, including 
- d3-graphviz
- https://github.com/mdaines/viz.js/ (may be the same or different from the one above)
- https://github.com/hpcc-systems/hpcc-js-wasm/

There are many interactive editors listed as https://graphviz.org/resources/#graphical-interfaces

**Comment by VladimirAlexiev** [comment]
https://github.com/magjac/d3-graphviz
https://bl.ocks.org/magjac/4acffdb3afbc4f71b448a210b5060bca: animated graph transitions
https://bl.ocks.org/magjac/69dc955a2e2ee085f60369c4a73f92a6

**Comment by l00mi** [comment]
@VladimirAlexiev thank you for the suggestions, we are looking for PR as this seem to be straight forward for you.

**Comment by VladimirAlexiev** [comment]
It's not straightforward. I'm just wondering why you started a graph layout tool from zero.

**Comment by l00mi** [comment]
We obviously did not start from zero, please check out the code. We also did tests with https://ialab.it.monash.edu/webcola/ (website not reachable currently) which we deemed as the most power-full and best fit so far, but it is not up-to-date anymore in regards to D3. 

We definitely plan to further improve this engine, but it is not easy without any further signals from the data itself (e.g. importance, hierarchy direction, etc.).

We plan to investigate which signal are best to inform a layout engine first (remember its all introspected here). And then in a second step to go further. As the rendering is implemented right now was successfully used together with customers. (It even found its way already in a paper http://www.semantic-web-journal.net/system/files/swj2746.pdf).

**Comment by VladimirAlexiev** [comment]
Is it this paper? http://www.semantic-web-journal.net/content/rescs-ontology-linking-open-research-data-multiple-sources-support-interdisciplinary

**Comment by l00mi** [comment]
exactly
