### ISSUE TITLE
Create a new project for the rdf-editor part.

### ISSUE THREAD

**Issue by l00mi** [zazuko/SPEX#41]
To channel feedback better and to have a proper own project with the only goal of RDF Sketching, create a new project independent of SPEX.

- [x] Create new project.
- [x] Deploy
- [x] Redirect https://spex.zazuko.com/#/rdf-editor to new deployment (link which most people use right now)
- [x] Move issues with `rdf-editor` label to new repo.

**Comment by martinmaillard** [comment]
New repo at https://github.com/zazuko/rdf-sketch, deployed at https://sketch.zazuko.com
