### ISSUE TITLE
Setting a default ontology(rdf) on page load

### ISSUE THREAD

**Issue by lavdim** [zazuko/SPEX#42]
Hi,

is it possible to set a default ontology (rdf) to the rdf-editor on the page load and make it read only, so the application will always visualize the same ontology.

Best,
Lavdim

**Comment by lavdim** [comment]
ok, I found it. It can be done as below:

    <script type="text/javascript">

      window.onload = function () {

        var content= `RDFContentHere`;
        var rdf = document.getElementsByTagName("rdf-editor");
        
        rdf[0].value = content;

        }

     </script> 

Thanks.

**Comment by l00mi** [comment]
Nice, but be advised.. before you build something with this.. there will be lots of change on this. Especially will we take this functionality out of this project. See #41

**Comment by lavdim** [comment]
I see. Thank you for the information.
