### ISSUE TITLE
Add possibility to switch all classes of

### ISSUE THREAD

**Issue by mchlrch** [zazuko/SPEX#44]
ATM all classes are switched on by default. On datasets with a lot of classes, the resulting visualization is not really useful.

Every class can be switched on/off independently, but there is no way to switch all classes off. Adding the possibility to switch all classes off at once would enable a user to explore a dataset with a lot of classes by first switching all classes off, followed by switching on a few classes selectively.

![image](https://user-images.githubusercontent.com/877232/139252525-4fe5b528-a0b1-4dbc-806f-8f0cbca6301c.png)

**Comment by BenjaminHofstetter** [comment]
implemented
