### ISSUE TITLE
Provide a way to Export Shapes

### ISSUE THREAD

**Issue by BenjaminHofstetter** [zazuko/SPEX#53]
I would like to use SPEX as a shape extraction tool. For that purpose it would be nice if I can export the shacl shape of a "Box" in SPEX. 

<img width="378" alt="Screenshot 2022-09-23 at 09 16 04" src="https://user-images.githubusercontent.com/8033981/191909924-ef0eb19a-6197-4f93-9694-abeed9c31203.png">

**Comment by ktk** [comment]
@BenjaminHofstetter it can be exported for all shapes on the top right "SHACL" button. I guess you mean just export a single shape and not all of them?

**Comment by BenjaminHofstetter** [comment]
Exactly one Shape and not all.

**Comment by BenjaminHofstetter** [comment]
This feature is implemented
