### ISSUE TITLE
Parser Error in SHACL Modal

### ISSUE THREAD

**Issue by BenjaminHofstetter** [zazuko/SPEX#69]
The produced RDF has issues with the conversion. 

`Uncaught (in promise) Error: Invliad concise-term string, prefixes are not allowed to start with an underscore: '_'``

This happens not always

**Comment by BenjaminHofstetter** [comment]
This is indeed the same thing

**Comment by tpluscode** [comment]
Fixed in `@rdfjs-elements/formats-pretty@0.5.2`

**Comment by BenjaminHofstetter** [comment]
fixes
